version: '2'
services:
  caliper:
    image: pfgray/caliper:sift
    ports:
      - "17000:9000"
    links:
      - couch
      - postgres
      - redis
    environment:
      NODE_ENV: production
      HOST_PROTOCOL: http
      HOST_DOMAIN: "${HOST_DOMAIN}"
      HOST_PORT: ""

      COUCH_HOST: couch
      COUCH_PORT: 5984
      COUCH_DB_NAME: sift

      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: sift
      PGUSER: caliper_administrator
      PGPASSWORD: pw

      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: pw

      ADMIN_USER: admin
      ADMIN_PW: password
  couch:
    image: klaemo/couchdb:2.0.0
    expose:
      - "5984"
  postgres:
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_USER: caliper_administrator
      POSTGRES_PASSWORD: pw
      POSTGRES_DB: sift
  redis:
    image: bitnami/redis:latest
    expose:
      - "6379"
    environment:
      REDIS_PASSWORD: pw