version: '2'
services:
  caliper:
    build: .
    ports:
      - "9000:9000"
    links:
      - couch
      - postgres
    environment:
      NODE_ENV: production
      COUCH_HOST: couch
      COUCH_PORT: 5984
      COUCH_DB_NAME: sift
      HOST_PROTOCOL: http
      HOST_DOMAIN: "${HOST_DOMAIN}"
      HOST_PORT: "${HOST_DOMAIN}"
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: sift
      PGUSER: admin
      PGPASSWORD: supersecret
  couch:
    image: klaemo/couchdb:2.0.0
    expose:
      - "5984"
  postgres:
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: sift
