version: '3'
services:
  caliper:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "6506:9000"
      - "9001:9001"
    links:
      - couch
      - postgres
      - redis
    environment:
      NODE_ENV: development
      HOST_PROTOCOL: http
      HOST_DOMAIN: "${HOST_DOMAIN}"
      HOST_PORT: "${HOST_DOMAIN}"

      COUCH_HOST: couch
      COUCH_PORT: 5984
      COUCH_DB_NAME: sift

      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: sift
      PGUSER: admin
      PGPASSWORD: supersecret

      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: reallysupersecret

      ADMIN_USER: administrator
      ADMIN_PW: password
    volumes:
      - './:/app'
      - /app/node_modules
  couch:
    image: klaemo/couchdb:2.0.0
    expose:
      - "5984"
  postgres:
    image: postgres
    expose:
      - "5432"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: sift
  redis:
    image: bitnami/redis:latest
    expose:
      - "6379"
    environment:
      REDIS_PASSWORD: reallysupersecret
